language: java
jdk: openjdk11
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: zhangz555
    token:
      secure: "hawrOatAGtO+PD813ARK52q/lNOol932DZ7kB8ZF4U899qs7F9KveQJuEfhPQlZv6Dczzc5acBNvP0FeXhnG3eV9ztyQLrzpqoKY+F4qkhrN5JlSHaO6qQRsBOgqbw6hzUN6hVyonZJFJku5ZQOwTrp/iNCUzEV2FkIWEuoHtgEMxEFJktPd0RzhDvPphUlIw9T9NcHMeqI9RhoG+b2bALYV0c/fOv76ETO0mJ1m/IlnHRzbwTs2wS0G9QovV5A1ujdTSd1noP/kDXuWo2ArLiBAo/kESBPJWQ26BfynUeQ5foijP0BM9Zmqw0nOyblE6gRMqnY6Z6lBPkZwUqUXq1hYDlqscB0xhe3x/NP8uQD6TqXjCB2wXGo78ibZVKc+A+dfMyQZ0/B/Zn9uHubw7GHHprITvAJ7TodrL3obpRPj/SWWh7wQmB2KYUSnMXPwRANkwkDlrhb7hSisuAKRTShp0eBWAN7ocSxd8M6OzrBILkbhZq63XQfMDK6iGw0G9vrryr2KsE56Bl1tg8xFO2M9T+8pM1rXbYcnrUaIjWITRORtq8edqAo0vMeh2yOxBcrj1ZBC1xSnotNPbV/z9RIhor/5qicXxfyFRddiO07M9Hy3IWYxSURL2iklpY1siNjQypCV6tjY0FQBGRdeA6gDBYKVa/UWrqTsKlSyrlY="

    
script:
  - ./mvnw clean install sonar:sonar -Dsonar.projectKey=zhangz555_CICDTraining
notifications:
  email:
    recipients:
      secure: "Q3EM9uQ7XXlDd6uE0WrtY2g9pXuawScm0xgwttRIYP/aMPHFkjPiFrCj/sJo3di6Z1OXUpwxmptVx8DHurhxKKmIIyGTgQNlwcJenIwHfbiVtDFbhqFLZGwadJKKHhxW0J2V3BZGgGjzHj/QnSc/Jayd0Jw1j/V5Bj/n/OB6r5AroiXhrNAcYCqKQil3flaA4KARMcz7RGjKAtJd7p8poq5vWc/ZxBzX/kfMt72pyqvTiAFIHmpC/VjbfIR7zrE8Qg4h7Ye7kJSX/GU1trXF02Sa/Cxz80aEDopaMSJPVDrG5/1MEUV1uWE+342rycb2Q9LcxA6Z+YOm3aNrtUeFqjYXYI5N7ahqJryQTZoDgq9Srq042LmGN7U/C7dxD0ykljw2yMXne97ysQfHTYlBrZ/bWN+dlg9gSDDzPF5PONmdlbEkXHeQd8uSMj3y3I6I6s0P3pz0k6JnMD7Sh0hYXxCLWC1qrqPLIb3wRSehOQJtmULJ9FczNYlpzdbMNLX3dIoko4YJ6ujFzjzBHsZ/OivjasM9kV+YZ1KSoq29Mi7pTW/xvZQdBsdjkiWy1mUe/hluObOrippVO+1+t3k2+N1RWoz9G9DWIUMds/NyQeTj/lOLqMUyjnRGeQiio64VSyT9PkP23TCZPxI08VdCHcSU8/QYJOkp6vjiA70XI0t6Q="

  on_failure: always
